x-cnf: &cnf
  networks:
    - ai-interviewee_app
  logging:
    driver: "json-file"
    options:
      max-size: "200k"

networks:
  ai-interviewee_app:
    name: ai-interviewee_app

services:
  postgres:
    image: postgres:16.2
    hostname: postgres
    container_name: pg_ai-interviewee
    restart: always
    ports:
      - "5869:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ai-interviewee
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    <<: *cnf

  keycloak_db:
    image: postgres:16.2
    container_name: keycloak_db_ai-interviewee
    hostname: ai-interviewee-keycloak_db
    volumes:
      - keycloak-pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5866:5432"
    <<: *cnf

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    container_name: keycloak_ai-interviewee
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KC_FEATURES: organization
    ports:
      - "8082:8080"
    command:
      - start-dev
    depends_on:
      - keycloak_db
    <<: *cnf

volumes:
  keycloak-pgdata:
